# Generated by Django 2.0.7 on 2018-07-18 13:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirtcastle_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='patterns',
            field=models.ManyToManyField(blank=True, related_name='_document_patterns_+', to='dirtcastle_api.Pattern'),
        ),
    ]
