version: "3"

services:

    mongo:
        image: mongo
        restart: always
        volumes:
            - mongo-data:/data/db

    api:
        build: .
        restart: always
        environment:
            MONGO_HOST: mongo
        volumes:
            - .:/api
        depends_on:
            - mongo
        ports:
            - "8000:8000"

volumes:
    mongo-data:
