version: "3"

services:

    db:
        image: postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data

    api:
        build: .
        entrypoint: python manage.py
        command: runserver 0.0.0.0:8000
        restart: always
        volumes:
            - .:/app
        environment:
            - DEBUG=true
        depends_on:
            - db
        ports:
            - "8000:8000"

volumes:
    db-data:
