version: "3"

services:

    mongo:
        image: mongo
        restart: always
        volumes:
            - mongo-data:/data/db

    api:
        build: .
        command: runserver --debug
        restart: always
        environment:
            API_HOST: 0.0.0.0
            MONGO_HOST: mongo
        volumes:
            - .:/api
        depends_on:
            - mongo
        ports:
            - "5000:5000"

volumes:
    mongo-data:
