# Generated by Django 2.0.7 on 2018-07-18 13:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('annotator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='unearth_api.Annotator')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='patterns',
            field=models.ManyToManyField(related_name='_document_patterns_+', to='unearth_api.Pattern'),
        ),
        migrations.AddField(
            model_name='annotator',
            name='patterns',
            field=models.ManyToManyField(blank=True, related_name='_annotator_patterns_+', to='unearth_api.Pattern'),
        ),
    ]
